//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS481_Hub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cs481Entities : DbContext
    {
        public cs481Entities()
            : base("name=cs481Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Available_API> Available_API { get; set; }
        public virtual DbSet<BLOG> BLOGs { get; set; }
        public virtual DbSet<USER_API_XREF> USER_API_XREF { get; set; }
        public virtual DbSet<USER_EXT> USER_EXT { get; set; }
    }
}
