//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS481_Hub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER_EXT
    {
        [Key]
        public string USER_ID { get; set; }
        public string FIRST_NM { get; set; }
        public string LAST_NM { get; set; }
        public string ZIPCODE { get; set; }
        public string void_ind { get; set; }
    }
}
