//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS481_Hub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER_API_XREF
    {
        [Key]
        public int API_ID { get; set; }
        public string USER_ID { get; set; }
        public string void_ind { get; set; }
    
        public virtual Available_API Available_API { get; set; }
    }
}
